### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by francisrod01** [thiagozanetti/react-intl-currency-input#10]
I just import `BrlCurrencyComponent` and I see this error.

TypeError: Cannot read property 'string' of undefined

Maybe, I import of wrong way. Please add `how to usage it` in the docs.

**Comment by hermesnetto** [comment]
I had the same problem, I just opened a PR to fix it. https://github.com/thiagozanetti/react-intl-currency-input/pull/11

**Comment by thiagozanetti** [comment]
A fix was addressed already. Please see #11
