### ISSUE TITLE
Suporte ao Typescript

### ISSUE THREAD

**Issue by GuiFerrari** [thiagozanetti/react-intl-currency-input#104]
Olá

Gostaria de saber se já foi implementado suporte ao typescript. Se sim, teria alguns exemplos de uso?

**Comment by thiagozanetti** [comment]
Acredito que você esteja falando dos type definitions. Ainda não parei pra ver isso pois não tive a necessidade ainda, mas vou aproveitar a deixa e começar a trabalhar nisso também. Caso você tenha bom conhecimento na gramática, pode contribuir com um PR também.

**Comment by danielbonifacio** [comment]
Algum update nisso? Estou prevendo utilizar a lib em um curso, mas não vejo como fazer isso sem suporte a TS.

Se tiver precisando de ajuda, @thiagozanetti estou disposto a ajudar a tipar isso melhor.

**Comment by thiagozanetti** [comment]
@danielbonifacio ficaria grato se pudesse desenrolar isso pra nós. Estou com pouquissimo tempo disponível nos últimos meses e não consegui dar andamento a essa issue.

**Comment by muxtardo** [comment]
Teve algum andamento nisso?

**Comment by felipemaccari** [comment]
essa ideia ainda ta aberta pra mandar uma PR? adoraria trabalhar nisso!

**Comment by muxtardo** [comment]
Seria MT bom

**Comment by thiagozanetti** [comment]
@felipemaccari se quiser trabalhar nisso, fique a vontade. Esse projeto está precisando de carinho e eu estou sem condições no momento. Aceito sugestões de como a gente pode fazer pra melhorar isso.

**Comment by thiagozanetti** [comment]
Resolvido no PR #373
