### ISSUE TITLE
Como integrar ao layout do material-ui

### ISSUE THREAD

**Issue by matheusoda** [thiagozanetti/react-intl-currency-input#111]
Bom dia, gostaria de saber se é possível utiliza-lo dentro de um componente do material-ui recebendo o estilo do componente .

**Comment by thiagozanetti** [comment]
@matheusoda conseguiu resolver o seu problema?

**Comment by matheusoda** [comment]
Sim sim, alterei a ordem dos componentes e aí ele herdou o css do outro componente

**Comment by sostenesg7** [comment]
A propiedade "component" não está na doc, basta passar o componente do material pra o IntlCurrencyInput, pela prop component.

Ex: 

```javascript
    <IntlCurrencyInput
      {...props}
      onChange={onChangeValue}
      currency="BRL"
      config={currencyConfig}
      component={TextField}
    />
```
