### ISSUE TITLE
Obter Name ou Id do input

### ISSUE THREAD

**Issue by lauraizabel** [thiagozanetti/react-intl-currency-input#148]
Olá! Bom dia,

Há alguma forma de obter o name ou id do input?

**Comment by thiagozanetti** [comment]
Olá @lauraizabel!

Te aconselho a leitura desse doc do React a respeito dos refs: https://pt-br.reactjs.org/docs/refs-and-the-dom.html. Acredito que isso vai te ajudar a conseguir a informação que precisa.

**Comment by lauraizabel** [comment]
Agradeço pela ajuda! 👍🏾
