### ISSUE TITLE
Carregar o input com valor pré definido

### ISSUE THREAD

**Issue by Williammanesco** [thiagozanetti/react-intl-currency-input#158]
Boa tarde!

Está funcionando corretamente quando o valor inicia zerado, mas ao carregar da minha API para alteraçao do campo, o valor é carregado sem as decimais. Como resolver?

Exemplo: 500,00 será salvo no banco 500

Ao carregar o valor para o input é apresentado 

R$ 5,00

Código:
```
import IntlCurrencyInput from "react-intl-currency-input"

const currencyConfig = {
  locale: "pt-BR",
  formats: {
    number: {
      BRL: {
        style: "currency",
        currency: "BRL",
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      },
    },
  },
};

function NumberFormatCustom(props) {
   const {inputRef, onChange, ...other} = props

   return (
      <IntlCurrencyInput 
      {...other } 
      currency="BRL" 
      config={currencyConfig}
      onChange={(e, value) => {
         onChange({
            target: {
               name: props.name,
               value: value
            }
         })
      }}
      />
   )

NumberFormatCustom.propTypes = {
   inputRef: PropTypes.func.isRequired,
   name: PropTypes.string.isRequired,
   onChange: PropTypes.func.isRequired,
};


export default function TextFieldMonetario (props) {
    return <TextField
            variant="outlined" 
            margin="normal" 
            InputProps={{
               inputComponent: NumberFormatCustom,
             }}
            {...props} />
}  
```

**Comment by thiagozanetti** [comment]
Para não perder a precisão, eu levo em consideração os decimais como digitos mais significativos fo valor inicial. Isso significa que o valor de R$500,00 no exemplo citado é tratado dentro do componente como o número 50000. Nesse caso você precisaria multiplicar o valor que retorna da sua API por 100 e somente depois devolver como valor inicial ao componente.

**Comment by thiagozanetti** [comment]
Somente no valor inicial, onde o componente não tem controle sobre o que está sendo inputado, é que precisa dessa manobra. O valor devolvido vai ser sempre o esperado.

**Comment by Williammanesco** [comment]
Obrigado!
