### ISSUE TITLE
Cannot resolve dependency 'big.js'

### ISSUE THREAD

**Issue by ulima69** [thiagozanetti/react-intl-currency-input#16]
Adicionado via yarn surge o erro:

node_modules\react-intl-currency-input\dist\format-currency.js:8:19: Cannot resolve dependency 'big.js'
   6 | exports.default = formatCurrency;
   7 | 
>  8 | var _big = require("big.js");
     |                    ^
   9 | 
  10 | var _big2 = _interopRequireDefault(_big);
  11 |

**Comment by thiagozanetti** [comment]
Fixed on 0.2.2
