### ISSUE TITLE
Space between prefix currency

### ISSUE THREAD

**Issue by gustavoferreirads** [thiagozanetti/react-intl-currency-input#17]
It's possible?

**Comment by thiagozanetti** [comment]
TL-DR: No.

The displayed value is provided by the Intl API and it is meant to be as is according to several standardization rules. You can learn more here: 
* https://tc39.es/ecma402/#sec-properties-of-intl-numberformat-instances
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
