### ISSUE TITLE
[Pergunta] É possível não iniciar o componente com um valor?

### ISSUE THREAD

**Issue by jonasmarco** [thiagozanetti/react-intl-currency-input#203]
Olá,

estou tendo alguns problemas com o plugin porque ele inicia o input com um valor (0,00), teria como por uma opção para isso ser definido nas props e poder configurar quando quero iniciar com valor ou não?

**Comment by thiagozanetti** [comment]
Não sei se entendi a pergunta mas existe uma propriedade chamada `defaultValue` onde você pode setar o valor inicial que desejar. 0,00 é somente um padrão e não é permitido iniciar sem um valor numérico ( outros caracteres talvez se apliquem dependendo da configuração do locale).

PS: Acabei de verificar que a referida propriedade não consta na documentação. Irei fazer a correção. Obrigado.

**Comment by thiagozanetti** [comment]
A correção foi feita aqui #205

**Comment by jonasmarco** [comment]
> ... não é permitido iniciar sem um valor numérico ...

Fala @thiagozanetti, explico novamente, o que eu queria era exatamente ao contrário disso, iniciar sem valor o input. Sem '0,00'.

Mesmo informando nada no `defaultValue` tenho problemas, mas não é com o seu componente, o que acontece é que uso um framework pai, no caso o `Ant Design` e no `Form` dele tem uma regra que não permite iniciar os componentes filhos com um valor, isso é definido nas configurações do próprio `Form` e ai ele acaba sobrescrevendo o do componente filho...

Mas enfim longa história. De qualquer forma obrigado pelo retorno.
