### ISSUE TITLE
Max Value Not Working

### ISSUE THREAD

**Issue by Mateus-pilo** [thiagozanetti/react-intl-currency-input#216]
Hey everyone, i have a problem  when i'm set max value the component doesn't work. 

See that:

```
    <Form.Item name="taxa" rules={[{ required: true, message: 'Campo obrigatório !' }, { max: 100, message: 'O maximo de percentual é 100' }]}>
          <StInputMasked max={100} defaultValue={fee} currency="BRL" config={currencyFinancial} onKeyPressCapture={handleTaxa} onChange={handleChange} />
    </Form.Item>
```

![image](https://user-images.githubusercontent.com/56692712/116937938-5c382580-ac40-11eb-8f7f-12d0faea390c.png)

Version:     "react-intl-currency-input": "^0.2.6",

**Comment by thiagozanetti** [comment]
Hey @Mateus-pilo thanks for reporting this. I'll check it and I'll come back to you yet this week.

**Comment by thiagozanetti** [comment]
@Mateus-pilo could you please explain me a little further what is happening? Is this a defaultValue or it is happening when you are editing?

**Comment by Mateus-pilo** [comment]
> @Mateus-pilo could you please explain me a little further what is happening? Is this a defaultValue or it is happening when you are editing?

Hey Thiago,
Isn't in default value, is in set value in execution

**Comment by wilclefison** [comment]
Some news about that?

**Comment by wilclefison** [comment]
My problem is case my default value is negative and the comparation in line 145 react-intl-currency-input/dist/index.js

calculatedValue  = -100
max = 10

145  if (!max || calculatedValue <= max) 

so if my calculated value is negative and max value is positive, it won't change.

**Comment by thiagozanetti** [comment]
Hey all,

There's a new release in place. Could you please check if the error still happens? I'm gonna close this issue by now but we can reopen it to discuss it further case the error persists.
