### ISSUE TITLE
BUG? Possibility to type negative numbers

### ISSUE THREAD

**Issue by PauloRodrigues33** [thiagozanetti/react-intl-currency-input#223]
Hello, i don't know if this is a bug...

I know i can press "minus" before prepend currency to make the value negative, but when i need transform an already typed value to negative and press "minus" the value and the mask return to 0.

Will be cool if i can press "minus" and the input toggle between positive and negative values automatically.

Thanks!!

**Comment by thiagozanetti** [comment]
There's a fix regarding negative values in #376. I ran a few tests myself and it seems working. To add a negative value you gonna need to add the value then prepend the minus signal at the leftmost side of the component, like this:

![Screenshot from 2023-03-08 21-15-30](https://user-images.githubusercontent.com/333482/223882316-beb5dcb7-b990-4a7f-90fd-388fcccfbc29.png)
