### ISSUE TITLE
Problema no Plataforma IOS Mobile

### ISSUE THREAD

**Issue by mateusdrag1** [thiagozanetti/react-intl-currency-input#235]
Ao tentar utilizar o componente no iphone, ele está perdendo o focus e levando a pagina para o topo, esse problema é algo conhecido ou não? 

Version: "react-intl-currency-input": "^0.2.6"

**Comment by thiagozanetti** [comment]
Olá @mateusdrag1! Não tinha conhecimento desse problema e também não tenho condições nesse momento de avaliar a situação por vários fatores mas o mais importante é que eu não tenho dispositivos da maçã. Fique a vontade para contribuir, o projeto é bem simples e toda contribuição é bem-vinda.

**Comment by sostenesg7** [comment]
@mateusdrag1 . Estás usando um componente personalizado?
Coloca teu código do input pra gente dar uma olhada.
Esse erro acontece quando o react renderiza e perde a referência do input, pela key.

Estava com esse problema aqui, pois estava usando o input do material, porém foi burrada minha, pois estava invertendo a ordem dos componentes, deveria passar a prop "component=InputDoMaterial", porém estava passando o componente de moeda para o material.

Nessa lib tem uma prop chamada component, que não aparece, por conta da tipagem que ainda não foi resolvida nela. Só passar teu componente nela.

```javascript
// @ts-ignore
<IntlCurrencyInput
  {...props}
  onChange={onChangeValue}
  currency="BRL"
  config={currencyConfig}
  component={FormTextInput}
/>
```

**Comment by mateusdrag1** [comment]
> ```js
> component={
> ```

![image](https://user-images.githubusercontent.com/10229087/129626029-fdf97006-8d7f-4227-90f2-8ef9536a38e4.png)

**Comment by thiagozanetti** [comment]
Após um longo inverno eu consegui retomar a este projeto. Algum dos senhores sabe dizer se essa situação foi resolvida? Vou fechar a issue por hora e se o erro continuar existindo a gente reabre e discute melhor.
