### ISSUE TITLE
Problema com NextJS em produção

### ISSUE THREAD

**Issue by rafaelnogueira1** [thiagozanetti/react-intl-currency-input#246]
Estou utilizando NextJS em minha aplicação estou tendo erro ao carregar a página utilizando SSR.
Quando acesso a página e dou refresh está quebrando apontando erro 500. Depois de muito buscar o porque vi que o problema está no uso desse pacote.
Rodando a aplicação local ou realizando build local, tudo funciona perfeitamente.
Alguém já teve esse problema? Alguma ideia do que pode estar acontecendo?

**Comment by felps-dev** [comment]
Especifique o output de erro, assim fica melhor para ajudar amigo.

**Comment by thiagozanetti** [comment]
Corrigido no #376
