### ISSUE TITLE
Problema no NextJs

### ISSUE THREAD

**Issue by eemr3** [thiagozanetti/react-intl-currency-input#351]
Estou utilizando NextJS em minha aplicação estou tendo erro ao carregar a página.
O erro esta no print abaixo:
 
![Captura de tela de 2022-09-19 16-31-39](https://user-images.githubusercontent.com/42968718/191100412-1f45c13a-1982-48e0-90e1-8324dc9e9d92.png)

Algum coisa que posso fazer?

**Comment by thiagozanetti** [comment]
@eemr3 o erro ainda persiste? Vou fechar a issue pois lancei uma versão nova e alguns bugs foram corrigidos. Caso o erro persista, a gente pode reabrir e discutir a respeito.

**Comment by eemr3** [comment]
Opa, na época eu acabei usando de outro artificil para obter o resultado que esperava, dai não testei mais a biblioteca, dai não posso dizer se perciste o erro. Mas obrigado por responder e pode fechar a issue :)
