### ISSUE TITLE
Suggestion: ability to remove the currency tag from the input

### ISSUE THREAD

**Issue by wyvern800** [thiagozanetti/react-intl-currency-input#458]
Hello, would it be possible to make a version that removes the R$ tag from the input, leaving only the formatted number itself?

**Comment by thiagozanetti** [comment]
Hey @wyvern800! Hope you're doing fine.

It is just a matter of changing the style from `currency` to `decimal` in the configuration.

**Comment by wyvern800** [comment]
Oh, is it. then sorry for the mistake <3
