### ISSUE TITLE
Currency symbol doesn't change when currency property is changed

### ISSUE THREAD

**Issue by ifeins** [thiagozanetti/react-intl-currency-input#6]
Hi,

I have an `AmountField` component in my project for inputting money amounts which leverages `IntlCurrencyInput` and is defined like so:

```
class AmountField extends Component {

    getCurrencyConfig(currency) {
        let currencyConfig = {
            locale: 'en-US',
            formats: {
                number: {

                }
            }
        }

        currencyConfig['formats']['number'][currency] = {style: 'currency', currency: currency}
        return currencyConfig
    }

    render() {
        return (
            <div className='amount-field'>
                <label>Amount</label>
                <IntlCurrencyInput currency={this.props.currency} 
                    config={this.getCurrencyConfig(this.props.currency)}
                    onChange={(event, value, maskedValue) => this.props.onAmountChanged(value)}/>
                    <div>
                        <hr/>
                    </div>
            </div>
        )
    }
}
```

The AmountField component is used like so:
`<AmountField currency={this.state.amountCurrency}/>`

I want to enable the user to change the currency (using a separate dropdown), but the problem is when I call `this.setState({amountCurrency: "EUR"})` then the symbol in the intl-currency-input remains the same. Only when I re-focus on the intl-currency-input then the currency symbol changes.

I've debugged this and the `AmountField` does get the new currency input upon change and passes it to the `IntlCurrencyInput` but there it seems that the change doesn't happen.

**Comment by ifeins** [comment]
Created a pull request to address this issue: https://github.com/thiagozanetti/react-intl-currency-input/pull/7

Can you review it?
Thanks

**Comment by ifeins** [comment]
Hey, thanks for merging the pull request.
Can you publish a new version to NPM?

The PR already updated `package.json` to the new version (0.1.9), so it just needs to be published.

**Comment by ifeins** [comment]
@thiagozanetti Sorry for pinging about this again, but can you publish the new version (0.1.9) to NPM (see my comment above)?

Thanks

**Comment by thiagozanetti** [comment]
@ifeins this is probably a very late response and I'm sorry about that. I published a new version with your fix a couple of weeks ago. 

Thank you for your time and cooperation.
