### ISSUE TITLE
Can't set min and max value

### ISSUE THREAD

**Issue by Tomekmularczyk** [thiagozanetti/react-intl-currency-input#8]
That would be really useful, I don't see anything about it in documentation.

**Comment by BernardoFBBraga** [comment]
I also needed this feature so I implemented it in a fork and added a pull request for it https://github.com/thiagozanetti/react-intl-currency-input/pull/12

**Comment by guilhermealbuquerquegit** [comment]
@thiagozanetti Nao vai implementar isso? Seria bastante interessante, por gentileza, dar uma ollhada!

**Comment by thiagozanetti** [comment]
@guilhermealbuquerquegit preciso de cenários onde um valor mínimo, diferente de 0 seria interessante. O  @BernardoFBBraga já implementou a lógica para o valor máximo, como comentado acima. Obrigado.
