### ISSUE TITLE
 Incorrect mask for nonzero value.

### ISSUE THREAD

**Issue by douglas-cavalcante** [thiagozanetti/react-intl-currency-input#88]
The mask is incorrect when the initial value is different from 0.

![image](https://user-images.githubusercontent.com/38563983/79794797-4acbf600-8329-11ea-91cc-c9ab80e7363c.png)

![image](https://user-images.githubusercontent.com/38563983/79795473-5cfa6400-832a-11ea-9c10-e2fe182d344a.png)

This bug occur when de default value isn't 0. Independent of the type and size

Solution: 
![image](https://user-images.githubusercontent.com/38563983/79795293-1147ba80-832a-11ea-8c63-c3f59e2934dd.png)

**Comment by thiagozanetti** [comment]
Thanks @douglas-cavalcante for reporting this issue. I'll have a look on this.

**Comment by thiagozanetti** [comment]
@douglas-cavalcante the issue was fixed on PR #91. Thanks once again.
