### ISSUE TITLE
Como iniciar o input vazio?

### ISSUE THREAD

**Issue by fmm312** [thiagozanetti/react-intl-currency-input#93]
Boa noite,

gostaria de saber como iniciar o input vazio, pois atualmente, por padrão ele é iniciado como **R$0,00**. Alguém poderia me ajudar?

**Comment by thiagozanetti** [comment]
@fmm312 ele sempre inicia como R$0,00 pois é o caso inicial pensado pra ele. Você poderia me explicar em que situação ele deveria ser iniciado vazio? Obrigado por entrar em contato.
