### ISSUE TITLE
Atualizei pra ultima versão 0.2.4 e agora ele não está respeitando o minimo de caracteres depois da , quando vai pra edição

### ISSUE THREAD

**Issue by AndreLZGava** [thiagozanetti/react-intl-currency-input#94]
Olá tudo bem?

Precisei atualizar o componente pra a versão 2.4 e ele não tem funcionado muito bem, quando estou usando sem centavos funciona normal ex: 20 reais quando vai pra edição aparece os 20, mas se eu salvar 20,50 na hora de mostrar ele está mostrando 2,05 verifiquei a documentação e não fala nada de atualizar a forma como passo os parâmetros da configuração acredito que seja um bug mesmo.

Aguardo retorno a respeito, desde já grato pela atenção.

**Comment by thiagozanetti** [comment]
@AndreLZGava por algum motivo eu não estava recebendo notificações a respeito desse repositório e por isso peço desculpa pela demora em responder. Vou verificar o problema e te dou uma resposta. Obrigado por entrar em contato.l

**Comment by thiagozanetti** [comment]
@AndreLZGava na última versão eu corrigi o problema relatado na issue #95 e acredito que seja o mesmo caso que o seu. Por favor teste e me dê um feedback. Vou fechar a issue como corrigida por hora mas se precisar a gente reabre. Obrigado.
