### ISSUE TITLE
Incorrect handling of tenth values

### ISSUE THREAD

**Issue by andrewfluck** [thiagozanetti/react-intl-currency-input#95]
Input renders values such as 0.1, 0.2, 2.5 as these respective values: 0.01, 0.01, 0.25

See: #96

**Comment by andrewfluck** [comment]
Issue #94 seems to be related, I only understand English though

**Comment by thiagozanetti** [comment]
@andrewfluck sorry about the delay. For some reason I unwatched this repo and therefore I was not receiving notifications regarding opened issues or PRs. I'll have a look on both the problem and the proposed fix. Thanks for reaching out.

**Comment by andrewfluck** [comment]
No problem, GitHub sends a lot of notifications sometimes haha
